<!--
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
-->

<!-- todo:optimize performance -->
<script lang="ts">
  // #region Imports
  import { T } from "@threlte/core"
  import { useGltfAnimations, useGltf } from "@threlte/extras"
  import { Group } from "three"
  import { MediaQuery } from "svelte/reactivity"
  // #endregion Imports

  // #region Responsive Media Query
  // 使用 Svelte 5 的 MediaQuery 类创建响应式媒体查询
  // fallback 参数设置为 false，表示在服务器端渲染时默认为非移动设备
  const mobileQuery = $state(new MediaQuery("max-width: 853px", false))

  // 使用 $derived 获取当前媒体查询结果
  const isMobile = $derived(mobileQuery.current)
  // #endregion Responsive Media Query

  // #region Responsive Properties
  // 根据媒体查询计算属性
  // 调整模型的缩放比例和位置
  const computedScale = $derived(isMobile ? 0.55 : 0.7) // 增大缩放比例
  const computedPosition = $derived(isMobile ? [0.8, 3, 7.5] : [0.5, 3, 9.5]) // 将模型放在中心位置
  // #endregion Responsive Properties

  // #region Props and Reactivity
  // Props with defaults using Svelte 5 runes
  let {
    scale = 0.7, // 使用静态默认值
    position = [0, 0, 0] as [number, number, number], // 使用静态默认值
    rotation = [60, 270, 210] as [number, number, number], // 保持原来的旋转值
  } = $props<{
    scale?: number
    position?: [number, number, number]
    rotation?: [number, number, number]
  }>()

  // 使用 $effect 监听 computedScale 和 computedPosition 的变化
  $effect(() => {
      scale = computedScale;

    if (position[0] === 0 && position[1] === 0 && position[2] === 0) { // 如果使用的是默认值
      position = computedPosition as [number, number, number];
    }
  })
  // #endregion Props and Reactivity

  // #region 3D Model Setup
  // Create a reference for the group using Svelte 5 runes
  let group = $state<Group | undefined>(undefined)

  // 为了调试，添加一个固定的位置值
  const yPosition = 0

  const gltf = useGltf("/models/tenhun_falling_spaceman_fanart.glb")
  const { actions } = useGltfAnimations<"Idle">(gltf)
  //   更新组件位置
  $effect(() => {
    if (group) {
      group.position.y = yPosition
    }
  })
  // #endregion 3D Model Setup

  // #region Animation Control
  // 动画状态
  let isAnimationPlaying = $state<boolean>(false)

  // 播放动画
  $effect(() => {
    // 当 actions 可用时自动播放动画
    if ($actions && $actions["Idle"]) {
      // 如果动画未播放，则播放动画
      if (!isAnimationPlaying) {
        // 设置动画为循环播放
        $actions["Idle"].reset().play()
        isAnimationPlaying = true
        console.log("Playing animation: Idle with increased amplitude")
      }
    }
  })

  // 导出触发动画的函数
  export function triggerAnimation() {
    if ($actions && $actions["Idle"]) {
      $actions["Idle"].play()
      isAnimationPlaying = true
      console.log("Manually playing animation: Idle")
    }
  }

  // 导出停止动画的函数
  export function stopAnimation() {
    if ($actions && $actions["Idle"]) {
      $actions["Idle"].stop()
      isAnimationPlaying = false
      console.log("Stopped animation: Idle")
    }
  }
  // #endregion Animation Control
</script>

<!-- #region 3D Model Rendering -->
{#if $gltf}
  <!-- #region Model Group Container -->
  <T.Group bind:ref={group} {rotation} {scale} {position}>
    <!-- #region GLTF Scene -->
    <T is={$gltf.scene} />
    <!-- #endregion GLTF Scene -->
  </T.Group>
  <!-- #endregion Model Group Container -->
{/if}
<!-- #endregion 3D Model Rendering -->
